import { CSSResultGroup, html, LitElement, PropertyValues, svg, SVGTemplateResult, TemplateResult } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import type { HassEntity } from "home-assistant-js-websocket";
import { forwardHaptic, LovelaceCard, LovelaceCardEditor } from "./ha";

import "./editor";
import type {
    LovelaceDomEvent,
    PredefinedPointConfig,
    ReplacedKey,
    RoomConfig,
    RoomConfigEventData,
    DreameVacuumCardConfig,
} from "./types/types";
import {
    ActionType,
    CalibrationPoint,
    CardPresetConfig,
    MapExtractorRoom,
    PredefinedZoneConfig,
    TranslatableString,
    VariablesStorage,
} from "./types/types";
import {
    ACTIVELY_CLEANING_STATES,
    ACTIVE_VACUUM_STATES,
    CARD_CUSTOM_ELEMENT_NAME,
    CARD_VERSION,
    DISCONNECTION_TIME,
    EDITOR_CUSTOM_ELEMENT_NAME,
    EMPTY_MAP_MODE,
    EVENT_AUTOGENERATED_CONFIG,
    EVENT_AUTOGENERATED_CONFIG_GET,
    EVENT_LOVELACE_DOM,
    EVENT_LOVELACE_DOM_DETAIL,
    EVENT_ROOM_CONFIG,
    EVENT_ROOM_CONFIG_GET,
    EVENT_SELECTION_CHANGED,
    EVENT_SERVICE_CALL,
    EVENT_SERVICE_CALL_GET,
    RESTING_VACUUM_STATES,
} from "./const";
import { localize, localizeWithHass } from "./localize/localize";
import PinchZoom from "./pinch-zoom";
import "./pinch-zoom";
import { ManualRectangle } from "./model/map_objects/manual-rectangle";
import { Context } from "./model/map_objects/context";
import { ManualPoint } from "./model/map_objects/manual-point";
import { ManualPath } from "./model/map_objects/manual-path";
import {
    checkIfEntitiesChanged,
    conditional,
    delay,
    getMousePosition,
    getWatchedEntities,
    hasConfigOrAnyEntityChanged,
    stopEvent,
} from "./utils";
import { buildSuggestedConfig, suggestForEntity } from "./utils/suggestion";
import { PredefinedPoint } from "./model/map_objects/predefined-point";
import { PredefinedMultiRectangle } from "./model/map_objects/predefined-multi-rectangle";
import { Room } from "./model/map_objects/room";
import { areAllEntitiesDefined, isOldConfig, validateConfig } from "./config-validators";
import { MapMode } from "./model/map_mode/map-mode";
import { SelectionType } from "./model/map_mode/selection-type";
import { RepeatsType } from "./model/map_mode/repeats-type";
import { PlatformGenerator } from "./model/generators/platform-generator";
import { CoordinatesConverter } from "./model/map_objects/coordinates-converter";
import { resolveCalibration, isCalibrationSourceConfigured } from "./model/map/calibration-resolver";
import { computeRobotOverlayGeometry, INITIAL_ROBOT_SAMPLE, RobotSample } from "./model/map/robot-overlay-geometry";
import { MapImageBuffer } from "./model/map/map-image-buffer";
import { RoomPickEngine } from "./model/map/room-pick-engine";
import { MapObject } from "./model/map_objects/map-object";
import { MousePosition } from "./model/map_objects/mouse-position";
import { HomeAssistantFixed } from "./types/fixes";
import { cardStyles } from "./card-styles";

import "./components/status-header";
import "./components/cleaning-mode-chip";
import "./components/tab-selector";
import "./components/action-buttons";
import "./components/cleaning-progress-bar";
import "./components/robot-animation";
import "./components/robot-marker";

/** Palette Dreame par défaut, indexée par color_index 0-3 */
const DEFAULT_ROOM_PALETTE: Record<number, number[]> = {
    0: [121, 170, 255],
    1: [255, 211, 38],
    2: [141, 210, 255],
    3: [150, 217, 141],
};

const windowWithCards = window as unknown as Window & { customCards: unknown[] };
windowWithCards.customCards = windowWithCards.customCards || [];
windowWithCards.customCards.push({
    type: CARD_CUSTOM_ELEMENT_NAME,
    name: "Dreame Vacuum Card",
    description: localize("common.description"),
    // Aperçu live dans le card picker via getStubConfig ; si aucune config n'est
    // possible (pas de vacuum/caméra), HA retombe proprement sur la description.
    preview: true,
    documentationURL: "https://github.com/foXaCe/dreame-vacuum-card",
    // HA 2026.6+ : auto-suggestion dans le card picker pour les entités vacuum.*
    // (seulement si une source de carte caméra/image existe — cf. suggestForEntity).
    getEntitySuggestion: suggestForEntity,
});

@customElement(CARD_CUSTOM_ELEMENT_NAME)
export class DreameVacuumCard extends LitElement {
    @state() private oldConfig = false;
    @state() private config!: DreameVacuumCardConfig;
    @state() private presetIndex!: number;
    @state() private realScale!: number;
    @state() private realImageWidth!: number;
    @state() private realImageHeight!: number;
    @state() private mapScale!: number;
    @state() private mapX!: number;
    @state() private mapY!: number;
    @state() public repeats = 1;
    @state() private selectedMode = 0;
    @state() private activeTab: "room" | "all" | "zone" = "all";
    @state() private mapLocked = true;
    @state() private configErrors: string[] = [];
    @state() private connected = false;
    /** Premier chargement de l'image de map effectué — pilote le skeleton (jamais
     *  ré-armé sur les rafraîchissements caméra pour éviter tout flicker). */
    @state() private mapLoaded = false;
    @state() public internalVariables = {};
    private currentPreset!: CardPresetConfig;
    private watchedEntities: string[] = [];
    private selectedManualRectangles: ManualRectangle[] = [];
    private selectedManualPoint?: ManualPoint;
    private selectedManualPath: ManualPath = new ManualPath([], this._getContext());
    private selectedPredefinedRectangles: PredefinedMultiRectangle[] = [];
    private selectedRooms: Room[] = [];
    private selectedPredefinedPoints: PredefinedPoint[] = [];
    private selectablePredefinedRectangles: PredefinedMultiRectangle[] = [];
    private selectableRooms: Room[] = [];
    private selectablePredefinedPoints: PredefinedPoint[] = [];
    private coordinatesConverter?: CoordinatesConverter;
    private entitiesToManuallyUpdate: string[] = [];
    private modes: MapMode[] = [];
    private shouldHandleMouseUp!: boolean;
    private lastHassUpdate!: Date;
    public isInEditor = false;
    // Double-buffering de l'image de carte (URL affichée vs préchargement en cours) :
    // voir `model/map/map-image-buffer.ts`. On ne bascule l'<img> visible qu'une fois la
    // nouvelle image décodée.
    private readonly _mapImageBuffer = new MapImageBuffer({
        resolveUrl: (path) => this.hass.hassUrl(path),
        onSwapped: () => this.requestUpdate(),
    });
    private _overlayDirty = false;
    private _cachedContext: Context | undefined;
    // Pick-canvas / hit-test / overlay de sélection des pièces : voir
    // `model/map/room-pick-engine.ts`. L'engine possède ses propres canvases off-screen et
    // caches ; le composant ne fournit que les accesseurs live (hass, converter, image DOM).
    private readonly _roomPickEngine = new RoomPickEngine({
        getMapImage: () => this._getMapImage(),
        getCameraState: () => this._getCameraState(),
        getConverter: () => this.coordinatesConverter,
    });
    /** Compat : `test-browser/{room-selection,segment-map-fallback,room-overlay-pixels}.test.ts`
     *  attendent la disponibilité du pick canvas via un cast direct sur l'instance de carte
     *  (`card._pickCanvas`). L'état réel vit désormais dans `_roomPickEngine` ; pas de modificateur
     *  `private` ici (accès externe volontaire) — sinon `noUnusedLocals` le signale comme mort
     *  puisque rien, à l'intérieur de la classe, ne le lit. */
    get _pickCanvas(): HTMLCanvasElement | null {
        return this._roomPickEngine.currentPickCanvas;
    }
    private _stateSensorId: string | null | undefined = undefined;
    private _stateSensorEntityKey: string | undefined = undefined;
    /** Interpolation du marqueur robot : cadence mesurée des échantillons vacuum_position
     *  (contrat §5.D — ~3 s de push cloud, la fluidité se gagne côté carte). Voir
     *  `model/map/robot-overlay-geometry.ts` pour le calcul pur associé. */
    private _robotSample: RobotSample = INITIAL_ROBOT_SAMPLE;

    constructor() {
        super();
        this._handleAutogeneratedConfigGet = this._handleAutogeneratedConfigGet.bind(this);
        this._handleRoomsConfigGet = this._handleRoomsConfigGet.bind(this);
        this._handleServiceCallGet = this._handleServiceCallGet.bind(this);
        this._handleLovelaceDomEvent = this._handleLovelaceDomEvent.bind(this);
    }

    @property({ attribute: false }) public _hass!: HomeAssistantFixed;

    public get hass(): HomeAssistantFixed {
        return this._hass;
    }

    public set hass(hass: HomeAssistantFixed) {
        const firstHass = !this._hass && hass;
        this._hass = hass;
        this.lastHassUpdate = new Date();
        if (firstHass) {
            this._firstHass();
        }
    }

    public static async getConfigElement(): Promise<LovelaceCardEditor> {
        return document.createElement(EDITOR_CUSTOM_ELEMENT_NAME);
    }

    public static getStubConfig(hass: HomeAssistantFixed): DreameVacuumCardConfig | undefined {
        const entities = Object.keys(hass.states);

        // Cherche en priorité une caméra/image avec `calibration_points` (intégrations
        // dreame_vacuum / xiaomi_miio). Sinon, accepte n'importe quelle caméra liée
        // à un device qui héberge aussi une entité vacuum.
        const cameras = entities.filter((e) => {
            const domain = e.substring(0, e.indexOf("."));
            return domain === "camera" || domain === "image";
        });
        const vacuums = entities.filter((e) => e.startsWith("vacuum."));
        if (cameras.length === 0 || vacuums.length === 0) {
            return undefined;
        }

        const calibrated = cameras.filter((e) => hass?.states[e]?.attributes?.["calibration_points"]);

        // Match camera ↔ vacuum par device_id (l'utilisateur peut avoir plusieurs robots).
        let pickedCamera = calibrated[0] ?? cameras[0];
        let pickedVacuum = vacuums[0];
        const cameraDeviceId = hass?.entities?.[pickedCamera]?.device_id;
        if (cameraDeviceId) {
            const matchingVacuum = vacuums.find((v) => hass?.entities?.[v]?.device_id === cameraDeviceId);
            if (matchingVacuum) pickedVacuum = matchingVacuum;
        } else {
            // Inverse : déduire la caméra à partir du device du premier vacuum trouvé.
            const vacuumDeviceId = hass?.entities?.[pickedVacuum]?.device_id;
            const matchingCamera = vacuumDeviceId
                ? cameras.find((c) => hass?.entities?.[c]?.device_id === vacuumDeviceId)
                : undefined;
            if (matchingCamera) pickedCamera = matchingCamera;
        }

        return buildSuggestedConfig(pickedCamera, pickedVacuum);
    }

    public setConfig(config: DreameVacuumCardConfig): void {
        if (!config) {
            throw new Error(this._localize("common.invalid_configuration"));
        }
        this.config = config;
        MapMode.debug = config.debug ?? false;
        if (isOldConfig(config)) {
            this.oldConfig = true;
            return;
        }
        this.configErrors = validateConfig(this.config);
        if (this.configErrors.length > 0) {
            return;
        }
        this.watchedEntities = getWatchedEntities(this.config);
        this._setPresetIndex(0, false, true);
        this.requestUpdate("config");
    }

    public getCardSize(): number {
        return 12;
    }

    /** API HA 2024.10+ : sections layout grid options.
     *  La grille d'une section HA fait 12 colonnes : `max_columns` est donc borné à 12
     *  (pleine largeur). `rows: "auto"` car la carte est content-driven (la hauteur de
     *  la map dépend du ratio de l'image caméra + contrôles) : un nombre fixe la
     *  clipperait via `.fit-rows` (ha-card est en overflow:hidden). `min/max_rows`
     *  restent des garde-fous si l'utilisateur force une hauteur via la poignée
     *  d'édition (sa `grid_options` gagne sur ce défaut). La méthode legacy
     *  `getLayoutOptions()` reste exposée comme fallback pour HA < 2024.10. */
    public getGridOptions() {
        return {
            columns: 12,
            min_columns: 6,
            max_columns: 12,
            rows: "auto" as const,
            min_rows: 6,
            max_rows: 20,
        };
    }

    public getLayoutOptions() {
        return {
            grid_columns: 4,
            grid_min_columns: 2,
            grid_rows: 10,
            grid_min_rows: 6,
        };
    }

    connectedCallback(): void {
        super.connectedCallback();
        if (this._isInEditor()) {
            window.addEventListener(EVENT_AUTOGENERATED_CONFIG_GET, this._handleAutogeneratedConfigGet);
            window.addEventListener(EVENT_ROOM_CONFIG_GET, this._handleRoomsConfigGet);
            window.addEventListener(EVENT_SERVICE_CALL_GET, this._handleServiceCallGet);
            this.isInEditor = true;
        }
        document.addEventListener(EVENT_LOVELACE_DOM, this._handleLovelaceDomEvent);
        this.connected = true;
        this._updateElements();
        this._initializeRooms();
        delay(100).then(() => this.requestUpdate());
    }

    disconnectedCallback(): void {
        super.disconnectedCallback();
        if (this._isInEditor()) {
            window.removeEventListener(EVENT_AUTOGENERATED_CONFIG_GET, this._handleAutogeneratedConfigGet);
            window.removeEventListener(EVENT_ROOM_CONFIG_GET, this._handleRoomsConfigGet);
            window.removeEventListener(EVENT_SERVICE_CALL_GET, this._handleServiceCallGet);
        }
        document.removeEventListener(EVENT_LOVELACE_DOM, this._handleLovelaceDomEvent);
        this.connected = false;
        if (this._throttledRenderTimer !== undefined) {
            clearTimeout(this._throttledRenderTimer);
            this._throttledRenderTimer = undefined;
        }
    }

    private _lastRenderTs = 0;
    private _throttledRenderTimer?: number;
    private static readonly _CLEANING_RENDER_MIN_MS = 200;

    protected shouldUpdate(changedProps: PropertyValues): boolean {
        if (!this.config) {
            return false;
        }
        const changed = hasConfigOrAnyEntityChanged(this.watchedEntities, changedProps, false, this.hass);
        if (!changed) return false;

        // Pendant un nettoyage actif, le coordinator HA pousse des updates toutes les ~1-3s.
        // On throttle CES ticks (~5 FPS max) pour éviter les rebuilds cascadés.
        // CRITIQUE : on ne throttle QUE quand la seule source de changement est `_hass` —
        // un requestUpdate() déclenché par une interaction utilisateur (toggle de pièce,
        // changement d'onglet, bouton) ne doit jamais être retardé.
        const changedKeys = Array.from(changedProps.keys());
        const isPureHassTick = changedKeys.length === 1 && changedKeys[0] === "_hass";
        if (isPureHassTick && this._isRobotActive()) {
            const now = Date.now();
            const dt = now - this._lastRenderTs;
            if (dt < DreameVacuumCard._CLEANING_RENDER_MIN_MS) {
                if (this._throttledRenderTimer === undefined) {
                    this._throttledRenderTimer = window.setTimeout(() => {
                        this._throttledRenderTimer = undefined;
                        this.requestUpdate();
                    }, DreameVacuumCard._CLEANING_RENDER_MIN_MS - dt);
                }
                return false;
            }
            this._lastRenderTs = now;
        }
        return true;
    }

    private _isRobotActive(): boolean {
        const preset = this.currentPreset;
        if (!preset?.entity) return false;
        const state = this.hass?.states?.[preset.entity]?.state;
        return !!state && ACTIVE_VACUUM_STATES.includes(state);
    }

    private _resolveStateSensor(entityId: string): string | null {
        if (this._stateSensorId !== undefined && this._stateSensorEntityKey === entityId) {
            return this._stateSensorId;
        }
        this._stateSensorEntityKey = entityId;
        const deviceId = this.hass?.entities?.[entityId]?.device_id;
        if (!deviceId) {
            this._stateSensorId = null;
            return null;
        }
        for (const [eid, entry] of Object.entries(this.hass.entities)) {
            if (entry.device_id !== deviceId || !eid.startsWith("sensor.")) continue;
            if (entry.translation_key === "state" || eid.endsWith("_state")) {
                this._stateSensorId = eid;
                if (!this.watchedEntities.includes(eid)) {
                    this.watchedEntities.push(eid);
                }
                return eid;
            }
        }
        this._stateSensorId = null;
        return null;
    }

    protected render(): TemplateResult | void {
        if (this.oldConfig) {
            return this._showOldConfig();
        }
        if (this.configErrors.length > 0) {
            return this._showConfigErrors(this.configErrors);
        }
        // hass peut ne pas être encore assigné (setConfig → premier render, preview éditeur).
        if (!this.hass) {
            return;
        }
        const invalidEntities = areAllEntitiesDefined(this.watchedEntities, this.hass);
        if (invalidEntities.length > 0) {
            return this._showInvalidEntities(invalidEntities);
        }

        const preset = this._getCurrentPreset();

        const stateSensorId = this._resolveStateSensor(preset.entity);
        const robotState = stateSensorId ? (this.hass.states[stateSensorId]?.state ?? "") : "";

        this._updateCalibration(preset);

        // Compute charger position as percentage of map image
        let chargerXPct = -1;
        let chargerYPct = -1;
        if (this.coordinatesConverter?.calibrated && preset.map_source?.camera) {
            const camState = this.hass.states[preset.map_source.camera];
            const chargerPos = camState?.attributes?.charger_position;
            if (chargerPos && chargerPos.x != null && chargerPos.y != null) {
                const mapCoords = this.coordinatesConverter.vacuumToMap(chargerPos.x, chargerPos.y);
                // Dimensions naturelles déjà cachées par _calculateBasicScale (@load de l'image) :
                // pas de lecture DOM dans le chemin chaud de render().
                const natW = this.realImageWidth;
                const natH = this.realImageHeight;
                if (natW && natH) {
                    chargerXPct = (mapCoords[0] / natW) * 100;
                    chargerYPct = (mapCoords[1] / natH) * 100;
                }
            }
        }

        // Compute robot position/heading as percentage of map image (option 2 anti-flash).
        // Résolution de l'overlay robot client-side :
        //  - un réglage explicite (preset puis config) est respecté, SAUF s'il demande
        //    l'overlay alors que l'intégration affirme dessiner déjà le robot dans le PNG ;
        //  - sinon « auto » : on l'active UNIQUEMENT si l'intégration a masqué le robot
        //    du PNG (attribut caméra `robot_in_map === false`). Zéro double-robot, suivi
        //    fluide (le marqueur glisse en CSS, sans recharger l'<img> à chaque déplacement).
        //
        // Le garde-fou sur le forçage vient d'un cas réel : l'éditeur matérialisait
        // `robot_overlay: true` tout seul à la moindre édition (cf. editor.ts, contrat §5.D),
        // et ce `true` hérité court-circuitait la protection. Sur une install dont l'entrée
        // d'intégration est antérieure au défaut « robot masqué » (les entrées existantes ne
        // sont jamais migrées), le PNG contient encore le robot : l'overlay s'ajoutait au
        // robot cuit et on voyait DEUX robots, celui du PNG en retard puisqu'il n'est
        // régénéré qu'à chaque rendu de carte. `robot_in_map === true` est une affirmation
        // de l'intégration, pas une supposition : on refuse alors le forçage.
        // L'attribut ABSENT (intégration antérieure au contrat) laisse le forçage
        // s'appliquer — c'est précisément à ça qu'il sert.
        const robotOverlayCfg = preset.robot_overlay ?? this.config?.robot_overlay;
        const robotCamState = preset.map_source?.camera ? this.hass.states[preset.map_source.camera] : undefined;
        const robotInMap = robotCamState?.attributes?.["robot_in_map"];
        let robotOverlayEnabled: boolean;
        if (typeof robotOverlayCfg === "boolean") {
            robotOverlayEnabled = robotOverlayCfg && robotInMap !== true;
        } else {
            robotOverlayEnabled = robotInMap === false;
        }
        // Le calcul de position/cap/cadence de glisse est délégué à une fonction pure
        // (voir model/map/robot-overlay-geometry.ts) ; seul l'état `_robotSample` persiste
        // d'un rendu à l'autre.
        const robotGeometry = computeRobotOverlayGeometry({
            camState: robotCamState,
            converter: this.coordinatesConverter,
            natW: this.realImageWidth,
            natH: this.realImageHeight,
            robotOverlayEnabled,
            prevSample: this._robotSample,
            nowMs: Date.now(),
            // Image affichée ≠ entity_picture courant (préchargement/reboot) :
            // le marqueur est gelé au lieu d'être recalculé sur des entrées
            // incohérentes (cf. robot-overlay-geometry.ts).
            mapSettling: !this._mapImageBuffer.isSettled(),
        });
        this._robotSample = robotGeometry.nextSample;
        const robotXPct = robotGeometry.xPct;
        const robotYPct = robotGeometry.yPct;
        const robotHeadingDeg = robotGeometry.headingDeg;
        const robotVisible = robotGeometry.visible;
        const robotIconUrl = robotGeometry.iconUrl;
        const robotBeamUrl = robotGeometry.beamUrl;

        const mapSrc = this._getMapSrc(preset);
        const platformsWithDefaultCalibration = PlatformGenerator.getPlatformsWithDefaultCalibration();
        const platformHasDefaultCalibration = platformsWithDefaultCalibration.includes(
            PlatformGenerator.getPlatformName(preset.vacuum_platform)
        );
        // `_updateCalibration` (appelée juste au-dessus dans ce même rendu) a déjà construit
        // `this.coordinatesConverter` : il est donc toujours défini ici. `platformHasDefaultCalibration`
        // ne sert plus que de filet de sécurité pour le cas (théorique) où il ne le serait pas
        // encore -- il ne doit PAS masquer un `calibrated === false` une fois le converter
        // construit, sinon une calibration réellement en échec (selfCheck dégénéré OU source
        // de calibration défaillante) ne serait jamais signalée pour les plateformes de cette
        // liste (Dreame, la seule à ce jour) : cf. constat plan 012, `plans/README.md`.
        const validCalibration = this.coordinatesConverter
            ? this.coordinatesConverter.calibrated
            : platformHasDefaultCalibration;
        // Distingue le message affiché quand la calibration n'est pas valide : une source
        // configurée qui a échoué (entité unknown/JSON invalide…) a un message dédié,
        // différent de « Invalid calibration » (points géométriquement dégénérés).
        const calibrationSourceFailed = !!this.coordinatesConverter?.calibrationSourceFailed;

        const hasSelection = this._hasActiveSelection();

        const mapZoomerContent = html`
            <div
                id="map-zoomer-content"
                style="
                 margin-top: ${(preset.map_source.crop?.top ?? 0) * -1}px;
                 margin-bottom: ${(preset.map_source.crop?.bottom ?? 0) * -1}px;
                 margin-left: ${(preset.map_source.crop?.left ?? 0) * -1}px;
                 margin-right: ${(preset.map_source.crop?.right ?? 0) * -1}px;"
            >
                <img
                    id="map-image"
                    alt="camera_image"
                    crossorigin="anonymous"
                    decoding="async"
                    loading="eager"
                    fetchpriority="high"
                    src="${mapSrc}"
                    @load="${() => {
                        this.mapLoaded = true;
                        this._calculateBasicScale();
                        this._buildPickCanvas();
                    }}"
                />

                <canvas id="room-selection-overlay"></canvas>

                <div id="map-image-overlay">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        version="2.0"
                        id="svg-wrapper"
                        class="${this.activeTab === "room" ? "room-mode" : ""}"
                        width="100%"
                        height="100%"
                        @mousedown="${(e: MouseEvent): void => this._mouseDown(e)}"
                        @mousemove="${(e: MouseEvent): void => this._mouseMove(e)}"
                        @mouseup="${(e: PointerEvent): void => this._mouseUp(e)}"
                        @click="${(e: MouseEvent): void => this._handleMapClick(e)}"
                    >
                        ${validCalibration ? this._drawSelection() : null}
                        ${validCalibration ? this._drawRooms() : null}
                    </svg>
                </div>
                <dreame-robot-animation
                    .robotState=${robotState}
                    .chargerX=${chargerXPct}
                    .chargerY=${chargerYPct}
                ></dreame-robot-animation>
                <dreame-robot-marker
                    .visible=${robotVisible}
                    .active=${this._isRobotActive()}
                    .xPercent=${robotXPct}
                    .yPercent=${robotYPct}
                    .headingDeg=${robotHeadingDeg}
                    .transitionMs=${robotGeometry.glideMs}
                    .iconUrl=${robotIconUrl}
                    .beamUrl=${robotBeamUrl}
                ></dreame-robot-marker>
            </div>
        `;

        return html`
            <ha-card
                data-appearance="${this.config.appearance ?? "premium"}"
                style="--map-scale: ${this.mapScale}; --real-scale: ${this.realScale};"
            >
                <div class="map-wrapper ${this.config.show_title ? "with-title" : ""}" part="map-wrapper">
                    <dreame-status-header
                        .hass=${this.hass}
                        .entityId=${preset.entity}
                        .showTitle=${this.config.show_title ?? false}
                    ></dreame-status-header>
                    <div class="map-container ${this.mapLoaded ? "" : "map-loading"}" part="map">
                        <pinch-zoom
                            min-scale="0.5"
                            id="map-zoomer"
                            @change="${this._calculateScale}"
                            two-finger-pan="${preset.two_finger_pan}"
                            locked="${this.mapLocked}"
                            no-default-pan="${this.mapLocked || preset.two_finger_pan}"
                            style="touch-action: none;"
                        >
                            ${mapZoomerContent}
                        </pinch-zoom>
                        ${this.mapLoaded ? null : html`<div id="map-skeleton" aria-hidden="true"></div>`}
                    </div>
                    <div id="map-zoomer-overlay">
                        <div class="map-zoom-icons">
                            <ha-icon
                                icon="${this.mapLocked ? "mdi:lock" : "mdi:lock-open-variant"}"
                                class="icon-on-map clickable ripple ${this.mapLocked ? "lock-active" : ""}"
                                role="button"
                                tabindex="0"
                                aria-pressed="${this.mapLocked ? "true" : "false"}"
                                aria-label="${this._localize(
                                    this.mapLocked ? "dreame_ui.map.unlock" : "dreame_ui.map.lock"
                                )}"
                                @click="${this._toggleMapLock}"
                                @keydown="${(e: KeyboardEvent) => this._handleIconKey(e, this._toggleMapLock)}"
                            ></ha-icon>
                            ${
                                this.activeTab === "zone"
                                    ? html`
                                          <ha-icon
                                              icon="mdi:plus"
                                              class="icon-on-map clickable ripple"
                                              role="button"
                                              tabindex="0"
                                              aria-label="${this._localize("dreame_ui.map.add_rectangle")}"
                                              @click="${() => this._addRectangle()}"
                                              @keydown="${(e: KeyboardEvent) =>
                                                  this._handleIconKey(e, () => this._addRectangle())}"
                                          ></ha-icon>
                                      `
                                    : null
                            }
                            ${
                                this.activeTab === "zone" || this.activeTab === "room"
                                    ? html`
                                          <div
                                              class="icon-on-map clickable ripple cycle-counter"
                                              role="button"
                                              tabindex="0"
                                              aria-label="${this._localize("dreame_ui.map.cycle_repeats")}"
                                              @click="${this._cycleRepeats}"
                                              @keydown="${(e: KeyboardEvent) => this._handleIconKey(e, this._cycleRepeats)}"
                                          >
                                              x${this.repeats}
                                          </div>
                                      `
                                    : null
                            }
                            <ha-icon
                                icon="mdi:image-filter-center-focus"
                                class="icon-on-map clickable ripple"
                                role="button"
                                tabindex="0"
                                aria-label="${this._localize("dreame_ui.map.recenter")}"
                                @click="${this._restoreMap}"
                                @keydown="${(e: KeyboardEvent) => this._handleIconKey(e, this._restoreMap)}"
                            ></ha-icon>
                        </div>
                    </div>
                </div>
                ${conditional(!validCalibration, () =>
                    calibrationSourceFailed
                        ? this._showCalibrationSourceFailedWarning()
                        : this._showInvalidCalibrationWarning()
                )}
                <dreame-cleaning-mode-chip .hass=${this.hass} .entityId=${preset.entity}></dreame-cleaning-mode-chip>
                <dreame-tab-selector
                    .activeTab=${this.activeTab}
                    .language=${this.hass?.locale?.language ?? ""}
                    @tab-changed=${(e: CustomEvent) => this._handleTabChange(e.detail.tab)}
                ></dreame-tab-selector>
                <dreame-cleaning-progress-bar
                    .hass=${this.hass}
                    .entityId=${preset.entity}
                ></dreame-cleaning-progress-bar>
                <dreame-action-buttons
                    .hass=${this.hass}
                    .entityId=${preset.entity}
                    .activeTab=${this.activeTab}
                    .hasSelection=${hasSelection}
                    .selectionCount=${this.selectedRooms.length + this.selectedPredefinedRectangles.length}
                    .canAppendRooms=${this._getRoomsInProgress().length > 0 && this.activeTab === "room"}
                    @action-run=${() => this._run(false)}
                    @action-append=${() => this._runAppend()}
                    @action-cancel=${() => this._clearSelection()}
                ></dreame-action-buttons>
            </ha-card>
        `;
    }

    private _hasActiveSelection(): boolean {
        return (
            this.selectedManualRectangles.length > 0 ||
            this.selectedRooms.length > 0 ||
            this.selectedPredefinedRectangles.length > 0 ||
            this.selectedPredefinedPoints.length > 0 ||
            !!this.selectedManualPoint
        );
    }

    private _handleTabChange(tab: "room" | "all" | "zone"): void {
        this.activeTab = tab;
        this._clearSelection();
        const modes = this.modes;
        switch (tab) {
            case "room": {
                const roomIdx = modes.findIndex((m) => m.selectionType === SelectionType.ROOM);
                if (roomIdx >= 0) this._setCurrentMode(roomIdx);
                break;
            }
            case "zone": {
                const zoneIdx = modes.findIndex((m) => m.selectionType === SelectionType.MANUAL_RECTANGLE);
                if (zoneIdx >= 0) {
                    this._setCurrentMode(zoneIdx);
                    // Attend le prochain rendu Lit puis ajoute le rectangle initial
                    this.updateComplete.then(() => this._addRectangle());
                }
                break;
            }
            case "all":
                // Mode "Toutes" : aucune interaction sur la carte, juste visualisation
                break;
        }
        this._overlayDirty = true;
        this.requestUpdate();
    }

    private _clearSelection(): void {
        this.selectedManualRectangles = [];
        this.selectedManualPoint = undefined;
        this.selectedManualPath = new ManualPath([], this._getContext());
        this.selectedPredefinedRectangles.forEach((r) => r.deselect());
        this.selectedPredefinedRectangles = [];
        this.selectedRooms.forEach((r) => r.deselect());
        this.selectedRooms = [];
        this.selectedPredefinedPoints.forEach((p) => p.deselect());
        this.selectedPredefinedPoints = [];
        this._overlayDirty = true;
        this.requestUpdate();
    }

    protected updated(changedProperties: PropertyValues): void {
        const oldHass = changedProperties.get("_hass") as HomeAssistantFixed | undefined;
        const changed =
            oldHass && this.hass && checkIfEntitiesChanged(this.entitiesToManuallyUpdate, oldHass, this.hass);
        this._updateElements(changed);
        this._maybeResetActiveSelection();

        if (this._overlayDirty) {
            this._overlayDirty = false;
            this._updateRoomSelectionOverlay();
        }
    }

    public _getCurrentPreset(): CardPresetConfig {
        return this.currentPreset;
    }

    /** État de l'entité caméra du preset courant, résolu à la demande — accesseur live
     *  injecté dans `_roomPickEngine` (voir model/map/room-pick-engine.ts). */
    private _getCameraState(): HassEntity | undefined {
        const cameraEntity = this._getCurrentPreset().map_source?.camera;
        return cameraEntity ? this.hass?.states[cameraEntity] : undefined;
    }

    private _getCalibration(config: CardPresetConfig): CalibrationPoint[] | undefined {
        return resolveCalibration(config, this.hass);
    }

    private _firstHass(): void {
        if (this.configErrors.length === 0 && !this.oldConfig) {
            this._setPresetIndex(0, false, true);
        }
    }

    private _setPresetIndex(index: number, user = false, force = false): void {
        if (index === this.presetIndex && !force) {
            return;
        }
        const config = this.config;
        if (!this.mapLocked) this._getPinchZoom()?.setTransform({ scale: 1, x: 0, y: 0, allowChangeEvent: true });
        if (user) {
            forwardHaptic("selection");
        }
        this.mapLocked = true;
        this.selectedMode = 0;
        this.realScale = 1;
        this.mapScale = 1;
        this.mapX = 0;
        this.mapY = 0;
        this._cachedContext = undefined;
        if (this.hass) this._updateCalibration(config);
        this.modes = this._getModes(config);

        this.presetIndex = index;
        this.internalVariables = this._getInternalVariables(config);

        // _setPreset assigne currentPreset + watchedEntities — source unique de vérité.
        this._setPreset(config);
        this._setCurrentMode(0, false);
        this._selectionChanged();
        this.requestUpdate();
    }

    private _getInternalVariables(config: CardPresetConfig): VariablesStorage {
        return {
            ...(PlatformGenerator.getVariables(config.vacuum_platform) ?? {}),
            ...(config.internal_variables ?? {}),
        };
    }

    private _getModes(config: CardPresetConfig) {
        const vacuumPlatform = PlatformGenerator.getPlatformName(config.vacuum_platform);
        return (
            (config.map_modes?.length ?? -1) === -1
                ? PlatformGenerator.generateDefaultModes(vacuumPlatform)
                : (config.map_modes ?? [EMPTY_MAP_MODE])
        ).map((m) => new MapMode(vacuumPlatform, m, this.config.language));
    }

    private _setPreset(config: CardPresetConfig): void {
        // Si la caméra change (preset multi-caméras), on purge les buffers d'image pour ne
        // jamais afficher transitoirement la carte de l'ancien robot/preset le temps que la
        // nouvelle image se décode (cf. double-buffering dans model/map/map-image-buffer.ts).
        if (this.currentPreset?.map_source?.camera !== config.map_source?.camera) {
            this._mapImageBuffer.reset();
            // Nouvelle source de map -> ré-arme le skeleton le temps du premier décodage.
            this.mapLoaded = false;
            // Nouveau robot/preset -> ne pas dérouler le cap à travers le changement (seul
            // le cap est réinitialisé ; posKey/posTs/glideMs survivent, comme avant migration
            // vers `_robotSample`).
            this._robotSample = { ...this._robotSample, headingDeg: undefined };
        }
        this.currentPreset = config;
        // Cast : getWatchedEntities attend la config complète de carte, mais ici on ne
        // fournit qu'un preset — type n'est utilisé nulle part dans le calcul des watched.
        this.watchedEntities = getWatchedEntities(config as DreameVacuumCardConfig);
    }

    private _lastCalibrationKey?: string;

    private _updateCalibration(config: CardPresetConfig): void {
        const calibrationPoints = this._getCalibration(config);
        // Une source de calibration explicitement configurée (entité, caméra, plateforme,
        // points bruts) qui ne produit aucun point exploitable est un ÉCHEC à signaler —
        // distinct d'une absence de configuration (identité implicite légitime). Voir
        // calibration-resolver.ts → isCalibrationSourceConfigured.
        const calibrationSourceFailed = calibrationPoints === undefined && isCalibrationSourceConfigured(config);
        // Clé stable sur la calibration : évite de recréer CoordinatesConverter à chaque render
        // (matrice affine/perspective recalculée = coûteux).
        const key = calibrationPoints ? JSON.stringify(calibrationPoints) : `none:${calibrationSourceFailed}`;
        if (key === this._lastCalibrationKey && this.coordinatesConverter) return;
        this._lastCalibrationKey = key;
        this.coordinatesConverter = new CoordinatesConverter(calibrationPoints, calibrationSourceFailed);
    }

    private _getMapSrc(config: CardPresetConfig): string {
        const cameraState = config.map_source.camera ? this.hass?.states?.[config.map_source.camera] : undefined;
        const entityPicture = cameraState?.attributes?.entity_picture;
        const isFresh =
            !!this.connected &&
            !!this.lastHassUpdate &&
            this.lastHassUpdate.getTime() + DISCONNECTION_TIME >= new Date().getTime();
        return this._mapImageBuffer.resolveSrc({
            mapSource: config.map_source,
            cameraEntityPicture: entityPicture,
            isFresh,
        });
    }

    private _getContext(): Context {
        if (!this._cachedContext) {
            this._cachedContext = new Context({
                scale: () => this.mapScale,
                realScale: () => this.realScale,
                mousePositionCalculator: (event) => this._getMousePosition(event),
                update: () => this.requestUpdate(),
                selectionChanged: () => this._selectionChanged(),
                coordinatesConverter: () => this.coordinatesConverter,
                selectedManualRectangles: () => this.selectedManualRectangles,
                selectedPredefinedRectangles: () => this.selectedPredefinedRectangles,
                selectedRooms: () => this.selectedRooms,
                selectedPredefinedPoint: () => this.selectedPredefinedPoints,
                roundingEnabled: () => this._getCurrentMode()?.coordinatesRounding ?? false,
                coordinatesToMetersDivider: () => this._getCurrentMode()?.coordinatesToMetersDivider ?? 1,
                maxSelections: () => this._getCurrentMode()?.maxSelections ?? 0,
                runImmediately: () => this._runImmediately(),
                localize: (string) => this._localize(string),
                getState: (entity) => this._hass.states[entity]?.state ?? "",
                toggleEntity: (entity) =>
                    this._hass.callService("homeassistant", "toggle", undefined, { entity_id: entity }),
                getCurrentMode: () => this._getCurrentMode(),
                activateRoomMode: () => this._activateRoomMode(),
                activeTab: () => this.activeTab,
            });
        }
        return this._cachedContext;
    }

    private _getMousePosition(event: MouseEvent | TouchEvent): MousePosition {
        return getMousePosition(event, this._getSvgWrapper(), this.mapScale);
    }

    private _setCurrentMode(newModeIndex: number, manual = true): void {
        const newMode = this.modes[newModeIndex];
        this.selectedManualRectangles = [];
        this.selectedManualPoint = undefined;
        this.selectedManualPath.clear();
        this.selectedPredefinedRectangles = [];
        // Réinitialiser l'état _selected de toutes les pièces avant de vider le tableau
        this.selectableRooms.forEach((room) => {
            room.deselect();
        });
        this.selectedRooms = [];
        this.selectedPredefinedPoints = [];
        this.selectablePredefinedRectangles = [];
        // Ne pas vider selectableRooms - les pièces doivent rester visibles en permanence
        // this.selectableRooms = [];
        this.selectablePredefinedPoints = [];

        switch (newMode?.selectionType) {
            case SelectionType.PREDEFINED_RECTANGLE:
                const zonesFromEntities = PredefinedMultiRectangle.getFromEntities(newMode, this.hass, () =>
                    this._getContext()
                );
                const manualZones = newMode.predefinedSelections
                    .map((ps) => ps as PredefinedZoneConfig)
                    .filter((pzc) => typeof pzc.zones !== "string")
                    .map((pzc) => new PredefinedMultiRectangle(pzc, this._getContext()));
                this.selectablePredefinedRectangles = zonesFromEntities.concat(manualZones);
                this.selectedPredefinedRectangles = this.selectablePredefinedRectangles.filter((s) => s.selected);
                this.entitiesToManuallyUpdate = newMode.predefinedSelections
                    .filter((s) => s.state_entity)
                    .map((s) => s.state_entity as string);
                break;
            case SelectionType.ROOM:
                // Ne recréer les pièces que si elles n'existent pas déjà
                if (this.selectableRooms.length === 0) {
                    this.selectableRooms = newMode.predefinedSelections.map(
                        (ps) => new Room(ps as RoomConfig, this._getContext())
                    );
                }
                this.selectedRooms = this.selectableRooms.filter((s) => s.selected);
                this.entitiesToManuallyUpdate = newMode.predefinedSelections
                    .filter((s) => s.state_entity)
                    .map((s) => s.state_entity as string);
                break;
            case SelectionType.PREDEFINED_POINT:
                const pointsFromEntities = PredefinedPoint.getFromEntities(newMode, this.hass, () =>
                    this._getContext()
                );
                const manualPoints = newMode.predefinedSelections
                    .map((ps) => ps as PredefinedPointConfig)
                    .filter((ppc) => typeof ppc.position !== "string")
                    .map((ppc) => new PredefinedPoint(ppc, this._getContext()));
                this.selectablePredefinedPoints = pointsFromEntities.concat(manualPoints);
                this.selectedPredefinedPoints = this.selectablePredefinedPoints.filter((s) => s.selected);
                this.entitiesToManuallyUpdate = newMode.predefinedSelections
                    .filter((s) => s.state_entity)
                    .map((s) => s.state_entity as string);
                break;
        }
        if (this.selectedMode != newModeIndex && manual) forwardHaptic("selection");
        this.selectedMode = newModeIndex;
        this._selectionChanged();
    }

    public _getCurrentMode(): MapMode | undefined {
        return this.modes[this.selectedMode];
    }

    public _getSelection(mode: MapMode | undefined): { selection: unknown[]; variables: VariablesStorage } {
        if (!mode) {
            return { selection: [], variables: {} };
        }
        const repeats = mode.repeatsType === RepeatsType.INTERNAL ? this.repeats : null;
        let selection: unknown[] = [];
        let variables: VariablesStorage = {};
        const variablesExtractor = (mos: Array<MapObject | undefined>): VariablesStorage => ({
            ...(mos[0]?.variables ?? {}),
            variables: mos.map((r) => r?.variables ?? {}),
        });
        switch (mode.selectionType) {
            case SelectionType.MANUAL_RECTANGLE:
                selection = this.selectedManualRectangles.map((r) => r.toVacuum(repeats));
                variables = variablesExtractor(this.selectedManualRectangles);
                break;
            case SelectionType.PREDEFINED_RECTANGLE:
                selection = this.selectedPredefinedRectangles
                    .map((r) => r.toVacuum(repeats))
                    .reduce((a, v) => a.concat(v), [] as unknown[]);
                variables = variablesExtractor(this.selectedPredefinedRectangles);
                break;
            case SelectionType.ROOM:
                const selectedRooms = this.selectedRooms
                    .map((r) => r.toVacuum())
                    .map((r) => DreameVacuumCard.adjustRoomId(r, mode));
                selection = [...selectedRooms, ...(repeats && selectedRooms.length > 0 ? [repeats] : [])];
                variables = variablesExtractor(this.selectedRooms);
                break;
            case SelectionType.MANUAL_PATH:
                selection = this.selectedManualPath.toVacuum(repeats);
                variables = variablesExtractor([this.selectedManualPath]);
                break;
            case SelectionType.MANUAL_POINT:
                selection = this.selectedManualPoint?.toVacuum(repeats) ?? [];
                variables = variablesExtractor([this.selectedManualPoint]);
                break;
            case SelectionType.PREDEFINED_POINT:
                selection = this.selectedPredefinedPoints
                    .map((p) => p.toVacuum(repeats))
                    .reduce((a, v) => a.concat(v), [] as unknown[]);
                variables = variablesExtractor(this.selectedPredefinedPoints);
                break;
        }
        if (mode.repeatsType === RepeatsType.REPEAT) {
            selection = Array(this.repeats)
                .fill(0)
                .flatMap(() => selection);
        }
        return { selection, variables };
    }

    private async _runImmediately(): Promise<boolean> {
        if (this._getCurrentMode()?.runImmediately ?? false) {
            await this._run(false);
            return true;
        }
        return false;
    }

    private _selectionChanged(): void {
        const currentMode = this._getCurrentMode();
        const { selection } = this._getSelection(currentMode);

        if (this.isInEditor) {
            const event: Event & { selection?: unknown } = new Event(EVENT_SELECTION_CHANGED);
            event.selection = selection ?? "[]";
            window.dispatchEvent(event);
        }

        // Marquer l'overlay comme devant être redessiné (sera fait dans updated() après le rendu Lit)
        this._overlayDirty = true;
        this.requestUpdate();
    }

    private _isInEditor(): boolean {
        function isInEditor(e: Element): boolean {
            return (
                (e.parentElement?.tagName?.toLowerCase() === "hui-card" &&
                    "preview" in (e.parentElement?.attributes ?? [])) ||
                (e.parentElement?.tagName?.toLowerCase() === "hui-section" &&
                    "preview" in (e.parentElement?.attributes ?? [])) ||
                e.parentElement?.tagName?.toLowerCase() === "hui-card-preview" ||
                (e.parentElement != null && isInEditor(e.parentElement)) ||
                (e.parentNode?.toString() == "[object ShadowRoot]" && isInEditor((e.getRootNode() as ShadowRoot).host))
            );
        }
        return isInEditor(this);
    }

    private async _handleAutogeneratedConfigGet(): Promise<void> {
        const event: Event & { presetConfig?: unknown } = new Event(EVENT_AUTOGENERATED_CONFIG);
        event.presetConfig = {
            ...this.config,
            map_modes: this._getModes(this.config).map((m) => m.toMapModeConfig()),
        };
        window.dispatchEvent(event);
    }

    private _handleRoomsConfigGet(): void {
        const event: Event & { roomConfig?: RoomConfigEventData } = new Event(EVENT_ROOM_CONFIG);
        event.roomConfig = this._getRoomsConfig();
        window.dispatchEvent(event);
    }

    private async _handleServiceCallGet(): Promise<void> {
        const currentPreset = this._getCurrentPreset();
        const currentMode = this._getCurrentMode();
        const { selection, variables } = this._getSelection(currentMode);
        if (selection.length === 0 || !currentMode) {
            forwardHaptic("failure");
        } else {
            const serviceCall = await currentMode.getServiceCall(
                this.hass,
                currentPreset.entity,
                selection,
                this.repeats,
                { ...this.internalVariables, ...variables }
            );
            const event: Event & { serviceCall?: string } = new Event(EVENT_SERVICE_CALL);
            event.serviceCall = JSON.stringify(serviceCall, null, 2);
            window.dispatchEvent(event);
        }
    }

    private async _handleLovelaceDomEvent(e: Event): Promise<void> {
        const lovelaceEvent = e as LovelaceDomEvent;
        if (
            EVENT_LOVELACE_DOM_DETAIL in lovelaceEvent.detail &&
            "action_handler_id" in lovelaceEvent.detail[EVENT_LOVELACE_DOM_DETAIL] &&
            lovelaceEvent.detail[EVENT_LOVELACE_DOM_DETAIL]["action_handler_id"] ===
                (this.config.action_handler_id ?? "this")
        ) {
            const details = lovelaceEvent.detail[EVENT_LOVELACE_DOM_DETAIL];
            if (details["action"] === undefined) return;
            const action = details["action"] as ActionType;
            const data = details["data"];
            const currentMode = this._getCurrentMode();
            switch (action) {
                case ActionType.CLEANING_START:
                    await this._run(false);
                    break;
                case ActionType.INTERNAL_VARIABLE_SET:
                    if (data) this._setInternalVariable(data["variable"], data["value"]);
                    break;
                case ActionType.MAP_MODE_NEXT:
                    this._setCurrentMode((this.selectedMode + 1) % this.modes.length, false);
                    break;
                case ActionType.MAP_MODE_PREVIOUS:
                    this._setCurrentMode((this.selectedMode - 1 + this.modes.length) % this.modes.length, false);
                    break;
                case ActionType.MAP_MODE_SET:
                    if (data && typeof data["index"] === "number") {
                        this._setCurrentMode(data["index"] % this.modes.length, false);
                    }
                    break;
                case ActionType.REPEATS_DECREMENT:
                    if (currentMode) {
                        this.repeats = ((this.repeats + currentMode.maxRepeats - 2) % currentMode.maxRepeats) + 1;
                    }
                    break;
                case ActionType.REPEATS_INCREMENT:
                    if (currentMode) {
                        this.repeats = (this.repeats % currentMode.maxRepeats) + 1;
                    }
                    break;
                case ActionType.REPEATS_SET:
                    if (currentMode && data && Number.isFinite(Number(data["value"]))) {
                        const max = currentMode.maxRepeats;
                        const requested = Math.trunc(Number(data["value"]));
                        // Modulo positif borné : repeats reste toujours dans [1, max] (jamais
                        // négatif, ce qui éviterait un RangeError sur Array(repeats) côté _run).
                        this.repeats = ((((requested - 1) % max) + max) % max) + 1;
                    }
                    break;
                case ActionType.SELECTION_CLEAR:
                    this._setCurrentMode(this.selectedMode);
                    break;
            }
        }
    }

    private _setInternalVariable(variable: string, value: ReplacedKey) {
        const newValues: VariablesStorage = { ...this.internalVariables };
        newValues[variable] = value;
        this.internalVariables = newValues;
        this.requestUpdate();
    }

    private _getRoomsConfig(): RoomConfigEventData | undefined {
        if (!this.hass) return undefined;
        const config = this._getCurrentPreset();
        const rooms = this.hass.states[config.map_source?.camera ?? ""]?.attributes["rooms"] as Record<
            string,
            MapExtractorRoom
        >;
        const roomsConfig = new Array<RoomConfig>();

        if (rooms) {
            const mode = this.modes.filter((m) => m.selectionType === SelectionType.ROOM).reverse()[0];
            const modeIndex = mode ? this.modes.indexOf(mode) : -1;

            for (const room_id in rooms) {
                if (!Object.prototype.hasOwnProperty.call(rooms, room_id)) continue;
                const room = rooms[room_id];

                if (!room.outline && !room.x0 && !room.y0 && !room.x1 && !room.y1) continue;
                if (room.visibility === "Hidden") continue;

                const outline = room.outline ?? [
                    [room.x0, room.y0],
                    [room.x1, room.y0],
                    [room.x1, room.y1],
                    [room.x0, room.y1],
                ];

                let roomColor: number[] | undefined = room.color ?? undefined;
                if (!roomColor && room.color_index != null) {
                    roomColor = DEFAULT_ROOM_PALETTE[room.color_index];
                }

                roomsConfig.push({
                    id: room_id,
                    icon: undefined,
                    label: undefined,
                    outline: outline,
                    color: roomColor,
                    color_index: room.color_index ?? undefined,
                } as RoomConfig);
            }

            return { modeIndex: modeIndex, rooms: roomsConfig };
        }
        return undefined;
    }

    private static adjustRoomId(roomId: string | number, config: MapMode): string | number {
        if (config.idType === "number") {
            const roomIdAsNumber = +roomId;
            return isNaN(roomIdAsNumber) ? roomId : roomIdAsNumber;
        }
        return roomId;
    }

    /** Pièces envoyées au dernier `_run()`. Permet de reconstituer la liste en cours quand
     *  l'utilisateur veut ajouter des pièces pendant un nettoyage actif — le robot ne
     *  supporte pas le "append" natif, donc on relance avec l'union des deux listes. */
    private _activeRoomSelection: (string | number)[] = [];

    private async _run(debug: boolean, extraRooms: (string | number)[] = []): Promise<void> {
        const currentPreset = this._getCurrentPreset();
        const currentMode = this._getCurrentMode();
        const { selection, variables } = this._getSelection(currentMode);

        // Fusionne extraRooms (pièces en cours côté robot) avec la sélection utilisateur,
        // en mode ROOM uniquement — les autres types de sélection n'ont pas la même forme.
        let finalSelection = selection;
        const isRoomMode = currentMode?.selectionType === SelectionType.ROOM;
        if (isRoomMode && extraRooms.length > 0) {
            // selection est [roomId1, roomId2, ..., repeats?]. On sépare le trailing repeats.
            const repeats = this.repeats;
            const selectionWithRepeats = currentMode.repeatsType === RepeatsType.INTERNAL;
            const selectedIds = selectionWithRepeats
                ? (selection.slice(0, -1) as (string | number)[])
                : (selection as (string | number)[]);
            const trailing = selectionWithRepeats ? [repeats] : [];
            const merged = Array.from(new Set([...extraRooms, ...selectedIds].map((v) => String(v)))).map((s) => {
                const asNum = Number(s);
                return Number.isNaN(asNum) ? s : asNum;
            });
            finalSelection = [...merged, ...trailing];
        }

        if (finalSelection.length === 0 || !currentMode) {
            forwardHaptic("failure");
        } else {
            const repeats = this.repeats;
            const serviceCall = await currentMode.getServiceCall(
                this.hass,
                currentPreset.entity,
                finalSelection,
                repeats,
                {
                    ...this.internalVariables,
                    ...variables,
                }
            );
            if (debug || (this.config.debug ?? false)) {
                const message = JSON.stringify(serviceCall, null, 2);
                console.info("[dreame-vacuum-card] Appel de service (debug) :\n" + message);
                forwardHaptic("success");
            } else {
                this.hass
                    .callService(serviceCall.domain, serviceCall.service, serviceCall.serviceData, serviceCall.target)
                    .then(
                        () => {
                            forwardHaptic("success");
                            // Mémorise la liste envoyée pour alimenter un éventuel "Ajouter" ultérieur.
                            if (isRoomMode) {
                                this._activeRoomSelection = (finalSelection as unknown[])
                                    .filter((v) => typeof v === "string" || typeof v === "number")
                                    .map((v) => v as string | number);
                            }
                        },
                        () => {
                            forwardHaptic("failure");
                        }
                    );
            }
        }
        if (currentPreset.clean_selection_on_start ?? true) {
            this._setCurrentMode(this.selectedMode);
        }
        this._selectionChanged();
    }

    /** Appelé par le bouton "+ Ajouter au nettoyage" : relance avec la liste active du robot
     *  plus la sélection courante. Utile pour étendre un nettoyage déjà en cours sans perdre
     *  les pièces déjà prévues (le robot les revisitera mais ça reste plus rapide que stop+restart). */
    private _runAppend(): Promise<void> {
        return this._run(false, this._getRoomsInProgress());
    }

    /** Récupère la liste des pièces "en cours". Source prioritaire : l'attribut
     *  `active_segments` exposé par l'intégration (fonctionne même si le nettoyage a été
     *  lancé depuis l'app Dreame ou un script HA). Fallback : la dernière sélection
     *  envoyée par la carte, mémorisée dans `_activeRoomSelection`. */
    private _getRoomsInProgress(): (string | number)[] {
        const knownRoomIds = new Set(this.selectableRooms.map((r) => String(r.toVacuum())));
        const preset = this.currentPreset;

        // Source 1 : attribut `active_segments` sur l'entité vacuum (intégration dreame_vacuum).
        const vacState = preset?.entity ? this.hass?.states?.[preset.entity] : undefined;
        const stateName = vacState?.state;
        const isActivelyCleaning = !!stateName && ACTIVELY_CLEANING_STATES.includes(stateName);
        if (isActivelyCleaning) {
            const raw = vacState?.attributes?.["active_segments"];
            if (Array.isArray(raw) && raw.length > 0) {
                const fromIntegration = raw
                    .map((v) => (typeof v === "number" ? v : Number(v)))
                    .filter((v) => Number.isFinite(v))
                    .map((v) => String(v))
                    .filter((id) => knownRoomIds.has(id));
                if (fromIntegration.length > 0) return fromIntegration;
            }
        }

        // Source 2 : mémoire locale — utile si l'intégration n'expose pas active_segments
        // (devices plus anciens) et que l'utilisateur a lancé depuis la carte.
        if (this._activeRoomSelection.length === 0) return [];
        return this._activeRoomSelection.filter((v) => knownRoomIds.has(String(v)));
    }

    /** Reset de la mémoire quand le robot retourne au repos. */
    private _maybeResetActiveSelection(): void {
        const preset = this.currentPreset;
        if (!preset?.entity) return;
        const state = this.hass?.states?.[preset.entity]?.state;
        if (!!state && RESTING_VACUUM_STATES.includes(state)) {
            this._activeRoomSelection = [];
        }
    }

    private _updateElements(somethingChanged = false): void {
        delay(10).then(() => this._calculateBasicScale());

        if (!somethingChanged) {
            return;
        }

        const update = () => {
            this._setCurrentMode(this.selectedMode);
            this.requestUpdate();
        };

        switch (this._getCurrentMode()?.selectionType) {
            case SelectionType.PREDEFINED_RECTANGLE:
                if (this.selectablePredefinedRectangles.filter((p) => p.isDynamic()).length > 0) update();
                break;
            case SelectionType.ROOM:
                if (this.selectedRooms.filter((p) => p.isDynamic()).length > 0) update();
                break;
            case SelectionType.PREDEFINED_POINT:
                if (this.selectablePredefinedPoints.filter((p) => p.isDynamic()).length > 0) update();
                break;
        }
    }

    private _handleMapClick(e: MouseEvent): void {
        if (this.activeTab !== "room") return;

        const room = this._hitTestRoom(e);
        if (room) {
            e.stopPropagation();
            room.toggleFromHitTest();
        }
    }

    private _drawRooms(): SVGTemplateResult | null {
        if (this.selectableRooms.length === 0) return null;
        // En mode Pièce, seuls les labels sont rendus — l'overlay canvas gère le visuel
        // Les polygones SVG de l'API sont décalés et inutilisables
        return svg`${this.selectableRooms.map((r) => r.renderLabelOnly())}`;
    }

    private _drawSelection(): SVGTemplateResult | null {
        // En mode "all", aucune sélection sur la carte (comme l'app Dreame)
        if (this.activeTab === "all") {
            return null;
        }
        switch (this._getCurrentMode()?.selectionType) {
            case SelectionType.MANUAL_RECTANGLE:
                return svg`${this.selectedManualRectangles.map((r) => r.render())}`;
            case SelectionType.PREDEFINED_RECTANGLE:
                return svg`${this.selectablePredefinedRectangles.map((r) => r.render())}`;
            case SelectionType.ROOM:
                // Les pièces sont déjà affichées par _drawRooms(), ne pas les afficher deux fois
                return null;
            case SelectionType.MANUAL_PATH:
                return svg`${this.selectedManualPath?.render()}`;
            case SelectionType.MANUAL_POINT:
                return svg`${this.selectedManualPoint?.render()}`;
            case SelectionType.PREDEFINED_POINT:
                return svg`${this.selectablePredefinedPoints.map((p) => p.render())}`;
            default:
                return null;
        }
    }

    private _addRectangle(): void {
        const preset = this._getCurrentPreset();
        const currentMode = this._getCurrentMode();
        const marginTop = preset.map_source.crop?.top ?? 0;
        const marginBottom = preset.map_source.crop?.bottom ?? 0;
        const marginLeft = preset.map_source.crop?.left ?? 0;
        const marginRight = preset.map_source.crop?.right ?? 0;
        this._calculateBasicScale();
        if (!currentMode || this.selectedManualRectangles.length >= currentMode.maxSelections) {
            forwardHaptic("failure");
            return;
        }
        const actualHeight = this.realImageHeight * this.realScale - marginTop - marginBottom;
        const actualWidth = this.realImageWidth * this.realScale - marginLeft - marginRight;
        const name = (this.selectedManualRectangles.length + 1).toString();
        const x = (actualWidth / 3 + marginLeft - this.mapX) / this.mapScale;
        const y = (actualHeight / 3 + marginTop - this.mapY) / this.mapScale;
        const width = actualWidth / 3 / this.mapScale;
        const height = actualHeight / 3 / this.mapScale;
        this.selectedManualRectangles.push(new ManualRectangle(x, y, width, height, name, this._getContext()));
        this._selectionChanged();
        forwardHaptic("selection");
        this.requestUpdate();
    }

    private _mouseDown(event: PointerEvent | MouseEvent | TouchEvent): void {
        if (event instanceof MouseEvent && event.button != 0) {
            return;
        }
        this.shouldHandleMouseUp = true;
    }

    private _mouseMove(event: MouseEvent | TouchEvent): void {
        if ((<Element>event.target).classList.contains("draggable")) {
            return;
        }
        this.selectedManualRectangles.filter((r) => r.isSelected()).forEach((r) => r.externalDrag(event));
        this.shouldHandleMouseUp = false;
    }

    private _mouseUp(event: PointerEvent | MouseEvent | TouchEvent): void {
        // En mode "all", aucune interaction sur la carte (comme l'app Dreame)
        if (this.activeTab === "all") {
            this.shouldHandleMouseUp = false;
            return;
        }

        const target = event.target as Element | null;
        // getAttribute("class") couvre uniformément HTMLElement et SVGElement sans
        // tomber sur le getter className (SVGAnimatedString) déprécié en TS 6.
        const classNames = target?.getAttribute?.("class") ?? "";
        const isRoomPolygon = classNames.includes("room-polygon");

        // Si le click provient d'un polygone de pièce, ne rien faire ici
        // Le handler du polygone va gérer le click
        if (isRoomPolygon) {
            this.shouldHandleMouseUp = false;
            return;
        }

        const currentMode = this._getCurrentMode();
        if (!(event instanceof MouseEvent && event.button != 0) && this.shouldHandleMouseUp && currentMode) {
            const { x, y } = getMousePosition(event, this._getSvgWrapper(), 1);
            switch (currentMode.selectionType) {
                case SelectionType.MANUAL_PATH:
                    forwardHaptic("selection");
                    this.selectedManualPath.addPoint(x, y);
                    this._selectionChanged();
                    stopEvent(event);
                    this.requestUpdate();
                    break;
                case SelectionType.MANUAL_POINT:
                    forwardHaptic("selection");
                    this.selectedManualPoint = new ManualPoint(x, y, this._getContext());
                    this._selectionChanged();
                    stopEvent(event);
                    this.requestUpdate();
                    break;
                default:
                    // Ne pas bloquer l'événement pour les autres modes (ROOM, etc.)
                    // L'événement doit se propager aux polygones des pièces
                    break;
            }
        }
        this.shouldHandleMouseUp = false;
    }

    private _toggleMapLock = (): void => {
        this.mapLocked = !this.mapLocked;
        forwardHaptic("selection");
    };

    private _cycleRepeats = (): void => {
        const maxRepeats = this._getCurrentMode()?.maxRepeats ?? 3;
        this.repeats = (this.repeats % maxRepeats) + 1;
        forwardHaptic("selection");
        this.requestUpdate();
    };

    private _handleIconKey(event: KeyboardEvent, action: () => void): void {
        if (event.key === "Enter" || event.key === " ") {
            event.preventDefault();
            action();
        }
    }

    private _restoreMap(): void {
        const zoomerContent = this._getMapZoomerContent();
        zoomerContent.style.transitionDuration = this._getCssProperty("--map-card-internal-transitions-duration");
        this._getPinchZoom().setTransform({ scale: 1, x: 0, y: 0, allowChangeEvent: true });
        this.mapScale = 1;
        forwardHaptic("selection");
        delay(300).then(() => (zoomerContent.style.transitionDuration = "0s"));
    }

    private _initializeRoomsRetries = 0;

    private _initializeRooms(): void {
        // Instance déconnectée : ne pas poursuivre la chaîne de retries (cf. connectedCallback).
        if (!this.connected) return;
        if (!this.modes || this.modes.length === 0) {
            if (this._initializeRoomsRetries >= 20) return;
            this._initializeRoomsRetries++;
            delay(500).then(() => this._initializeRooms());
            return;
        }
        this._initializeRoomsRetries = 0;

        const roomMode = this.modes.find(
            (m) => m.config.template === "vacuum_clean_segment" || m.selectionType === SelectionType.ROOM
        );

        if (!roomMode) return;

        if (roomMode.predefinedSelections && roomMode.predefinedSelections.length > 0) {
            this.selectableRooms = roomMode.predefinedSelections.map(
                (s) => new Room(s as RoomConfig, this._getContext())
            );
            this.requestUpdate();
            return;
        }

        const roomsConfig = this._getRoomsConfig();

        if (roomsConfig && roomsConfig.rooms.length > 0) {
            if (!roomMode.predefinedSelections || roomMode.predefinedSelections.length === 0) {
                roomMode.predefinedSelections = roomsConfig.rooms;
            }
            this.selectableRooms = roomsConfig.rooms.map((s) => new Room(s as RoomConfig, this._getContext()));
            this.requestUpdate();
        }
    }

    private _activateRoomMode(): void {
        // Cherche le mode vacuum_clean_segment ou un mode avec ROOM selection type
        let roomMode = this.modes.findIndex((m) => m.config.template === "vacuum_clean_segment");

        // Si vacuum_clean_segment n'existe pas, chercher un mode avec ROOM
        if (roomMode === -1) {
            roomMode = this.modes.findIndex((m) => m.selectionType === SelectionType.ROOM);
        }

        if (roomMode !== -1) {
            this._setCurrentMode(roomMode, true);
            forwardHaptic("selection");
        }
    }

    private _getCssProperty(property: string): string {
        return getComputedStyle(this._getMapImage()).getPropertyValue(property);
    }

    private _calculateBasicScale(): void {
        const mapImage = this._getMapImage();
        if (mapImage && mapImage.naturalWidth > 0) {
            this.realImageWidth = mapImage.naturalWidth;
            this.realImageHeight = mapImage.naturalHeight;
            this.realScale = mapImage.width / mapImage.naturalWidth;
        }
    }

    /**
     * Pick buffer : canvas dont le canal bleu encode l'ID de segment de chaque pièce.
     * Délègue à `_roomPickEngine` (voir model/map/room-pick-engine.ts) — cette méthode reste
     * un simple point d'entrée nommé pour ne pas toucher ses appelants (template `@load`,
     * `_updateRoomSelectionOverlay`, `_hitTestRoom`).
     */
    private _buildPickCanvas(): void {
        this._roomPickEngine.ensurePickCanvas();
    }

    /**
     * Overlay style Dreame : toute la carte assombrie sauf les pièces sélectionnées.
     * Résout les éléments du shadow DOM (seul le composant y a accès) puis délègue le dessin
     * à `_roomPickEngine`.
     */
    private _updateRoomSelectionOverlay(): void {
        const overlayCanvas = this.shadowRoot?.getElementById("room-selection-overlay") as HTMLCanvasElement | null;
        if (!overlayCanvas) return;

        if (this.activeTab === "room") {
            this._buildPickCanvas();
        }
        const mapImg = this.shadowRoot?.getElementById("map-image") as HTMLImageElement | null;
        this._roomPickEngine.drawSelectionOverlay(overlayCanvas, mapImg, this.selectedRooms, this.activeTab);
    }

    /**
     * Hit-test pixel-perfect : coordonnées de clic → Room sélectionnable. La conversion en
     * coordonnées normalisées (seule dépendance au DOM réel, `getBoundingClientRect`) reste
     * ici ; la résolution pixel-perfect (canal bleu → room ID) est déléguée à l'engine.
     */
    private _hitTestRoom(event: MouseEvent): Room | null {
        if (this.selectableRooms.length === 0) return null;

        this._buildPickCanvas();

        const mapImage = this._getMapImage();
        if (!mapImage) return null;

        const rect = mapImage.getBoundingClientRect();
        const relX = (event.clientX - rect.left) / rect.width;
        const relY = (event.clientY - rect.top) / rect.height;

        const logicalId = this._roomPickEngine.hitTest(relX, relY);
        if (logicalId === undefined) return null;

        return this.selectableRooms.find((r) => String(r.toVacuum()) === String(logicalId)) ?? null;
    }

    private _calculateScale(): void {
        const pinchZoom = this._getPinchZoom();
        if (!pinchZoom) return;
        this.mapScale = pinchZoom.scale;
        this.mapX = pinchZoom.x;
        this.mapY = pinchZoom.y;
    }

    private _getPinchZoom(): PinchZoom {
        return this.shadowRoot?.getElementById("map-zoomer") as PinchZoom;
    }

    private _getMapImage(): HTMLImageElement {
        return this.shadowRoot?.getElementById("map-image") as HTMLImageElement;
    }

    private _getMapZoomerContent(): HTMLElement {
        return this.shadowRoot?.getElementById("map-zoomer-content") as HTMLElement;
    }

    private _getSvgWrapper(): SVGGraphicsElement {
        return this.shadowRoot?.querySelector("#svg-wrapper") as SVGGraphicsElement;
    }

    private _showConfigErrors(errors: string[]): TemplateResult {
        errors.forEach((e) => console.error(e));
        const errorCard = document.createElement("hui-error-card") as LovelaceCard;
        try {
            errorCard.setConfig({
                type: "error",
                error: errors[0],
                origConfig: this.config,
            });
            return html` ${errorCard} `;
        } catch {
            return html` <pre style="padding: 10px; background-color: red;">${errors[0]}</pre> `;
        }
    }

    private _showOldConfig(): TemplateResult {
        return html`
            <hui-warning>
                <h1>Xiaomi Vacuum Map Card ${CARD_VERSION}</h1>
                <p>${this._localize("common.old_configuration")}</p>
                <p>
                    <a href="https://github.com/foXaCe/dreame-vacuum-card#migrating-from-v1xx" target="_blank"
                        >${this._localize("common.old_configuration_migration_link")}</a
                    >
                </p>
            </hui-warning>
        `;
    }

    private _showInvalidEntities(entities: string[]): TemplateResult {
        return html`
            <hui-warning>
                <h1>${this._localize("validation.invalid_entities")}</h1>
                <ul>
                    ${entities.map(
                        (e) =>
                            html` <li>
                                <pre>${e}</pre>
                            </li>`
                    )}
                </ul>
            </hui-warning>
        `;
    }

    private _showInvalidCalibrationWarning(): TemplateResult {
        return html` <hui-warning>${this._localize("validation.invalid_calibration")}</hui-warning> `;
    }

    /** Source de calibration explicitement configurée (entité/caméra/plateforme/points)
     *  mais qui n'a produit aucun point exploitable — distinct de `_showInvalidCalibrationWarning`
     *  (points géométriquement dégénérés) : ici, la source elle-même est en échec (entité
     *  "unknown"/"unavailable", JSON invalide, attribut absent…). Voir CoordinatesConverter
     *  → `calibrationSourceFailed`. */
    private _showCalibrationSourceFailedWarning(): TemplateResult {
        return html` <hui-warning>${this._localize("validation.calibration_source_failed")}</hui-warning> `;
    }

    private _localize(ts: TranslatableString): string {
        return localizeWithHass(ts, this.hass, this.config);
    }

    static get styles(): CSSResultGroup {
        return cardStyles;
    }
}
